namespace AccessibleWindowsToolkit.Models;

public sealed record Candidate(string Id, string DisplayName, string Category, string Method);

public static class CandidateCatalog
{
    public static readonly Candidate[] All =
    {
        new("Clipchamp.Clipchamp", "Clipchamp", "Microsoft", "Appx"),
        new("Microsoft.3DBuilder", "3D Builder", "Microsoft", "Appx"),
        new("Microsoft.549981C3F5F10", "Cortana", "Microsoft", "Appx"),
        new("Microsoft.BingFinance", "Bing Finance", "Microsoft", "Appx"),
        new("Microsoft.BingFoodAndDrink", "Bing Food And Drink", "Microsoft", "Appx"),
        new("Microsoft.BingHealthAndFitness", "Bing Health And Fitness", "Microsoft", "Appx"),
        new("Microsoft.BingNews", "Bing News", "Microsoft", "Appx"),
        new("Microsoft.BingSports", "Bing Sports", "Microsoft", "Appx"),
        new("Microsoft.BingTranslator", "Bing Translator", "Microsoft", "Appx"),
        new("Microsoft.BingTravel", "Bing Travel", "Microsoft", "Appx"),
        new("Microsoft.BingWeather", "Bing Weather", "Microsoft", "Appx"),
        new("XP9CXNGPPJ97XX", "Microsoft Copilot", "Microsoft", "WinGet"),
        new("Microsoft.Windows.AIHub", "Copilot+ AI Hub", "Microsoft", "Appx"),
        new("Microsoft.PCManager", "Microsoft PC Manager", "Microsoft", "Appx"),
        new("Microsoft.Messaging", "Messaging", "Microsoft", "Appx"),
        new("Microsoft.Microsoft3DViewer", "3D Viewer", "Microsoft", "Appx"),
        new("Microsoft.MicrosoftJournal", "Microsoft Journal", "Microsoft", "Appx"),
        new("Microsoft.MicrosoftOfficeHub", "Office Hub", "Microsoft", "Appx"),
        new("Microsoft.MicrosoftPowerBIForWindows", "Power BI", "Microsoft", "Appx"),
        new("Microsoft.MicrosoftSolitaireCollection", "Solitaire Collection", "Microsoft", "Appx"),
        new("Microsoft.MicrosoftStickyNotes", "Sticky Notes", "Microsoft", "Appx"),
        new("Microsoft.MixedReality.Portal", "Mixed Reality Portal", "Microsoft", "Appx"),
        new("Microsoft.NetworkSpeedTest", "Network Speed Test", "Microsoft", "Appx"),
        new("Microsoft.News", "Microsoft News", "Microsoft", "Appx"),
        new("Microsoft.Office.OneNote", "OneNote (UWP)", "Microsoft", "Appx"),
        new("Microsoft.Office.Sway", "Sway", "Microsoft", "Appx"),
        new("Microsoft.OneConnect", "One Connect / Mobile Plans", "Microsoft", "Appx"),
        new("Microsoft.Print3D", "Print 3D", "Microsoft", "Appx"),
        new("Microsoft.PowerAutomateDesktop", "Power Automate Desktop", "Microsoft", "Appx"),
        new("Microsoft.SkypeApp", "Skype (UWP)", "Microsoft", "Appx"),
        new("Microsoft.Todos", "Microsoft To Do", "Microsoft", "Appx"),
        new("Microsoft.Windows.DevHome", "Dev Home", "Microsoft", "Appx"),
        new("Microsoft.WindowsAlarms", "Alarms & Clock", "Microsoft", "Appx"),
        new("Microsoft.WindowsFeedbackHub", "Feedback Hub", "Microsoft", "Appx"),
        new("Microsoft.WindowsMaps", "Windows Maps", "Microsoft", "Appx"),
        new("Microsoft.WindowsSoundRecorder", "Sound Recorder", "Microsoft", "Appx"),
        new("Microsoft.XboxApp", "Xbox Console Companion", "Xbox", "Appx"),
        new("Microsoft.ZuneVideo", "Movies & TV", "Microsoft", "Appx"),
        new("MicrosoftCorporationII.MicrosoftFamily", "Family Safety", "Microsoft", "Appx"),
        new("MicrosoftCorporationII.QuickAssist", "Quick Assist", "Microsoft", "Appx"),
        new("MicrosoftTeams", "Microsoft Teams (Old)", "Microsoft", "Appx"),
        new("MSTeams", "Microsoft Teams (New)", "Microsoft", "TeamsNew"),
        new("ACGMediaPlayer", "ACG Media Player", "ThirdParty", "Appx"),
        new("ActiproSoftwareLLC", "Actipro Software", "ThirdParty", "Appx"),
        new("AdobeSystemsIncorporated.AdobePhotoshopExpress", "Adobe Photoshop Express", "ThirdParty", "Appx"),
        new("Amazon.com.Amazon", "Amazon", "ThirdParty", "Appx"),
        new("AmazonVideo.PrimeVideo", "Prime Video", "ThirdParty", "Appx"),
        new("Asphalt8Airborne", "Asphalt 8", "ThirdParty", "Appx"),
        new("AutodeskSketchBook", "Autodesk SketchBook", "ThirdParty", "Appx"),
        new("CaesarsSlotsFreeCasino", "Caesars Slots", "ThirdParty", "Appx"),
        new("COOKINGFEVER", "Cooking Fever", "ThirdParty", "Appx"),
        new("CyberLinkMediaSuiteEssentials", "CyberLink Media Suite", "ThirdParty", "Appx"),
        new("DisneyMagicKingdoms", "Disney Magic Kingdoms", "ThirdParty", "Appx"),
        new("Disney.37853FC22B2CE", "Disney+", "ThirdParty", "Appx"),
        new("DrawboardPDF", "Drawboard PDF", "ThirdParty", "Appx"),
        new("Duolingo-LearnLanguagesforFree", "Duolingo", "ThirdParty", "Appx"),
        new("EclipseManager", "Eclipse Manager", "ThirdParty", "Appx"),
        new("FACEBOOK.FACEBOOK", "Facebook", "ThirdParty", "Appx"),
        new("FarmVille2CountryEscape", "FarmVille 2", "ThirdParty", "Appx"),
        new("Flipboard", "Flipboard", "ThirdParty", "Appx"),
        new("HiddenCity", "Hidden City", "ThirdParty", "Appx"),
        new("HULULLC.HULUPLUS", "Hulu", "ThirdParty", "Appx"),
        new("iHeartRadio", "iHeartRadio", "ThirdParty", "Appx"),
        new("Facebook.Instagram", "Instagram", "ThirdParty", "Appx"),
        new("king.com.BubbleWitch3Saga", "Bubble Witch 3", "ThirdParty", "Appx"),
        new("king.com.CandyCrushSaga", "Candy Crush Saga", "ThirdParty", "Appx"),
        new("king.com.CandyCrushSodaSaga", "Candy Crush Soda", "ThirdParty", "Appx"),
        new("LinkedInforWindows", "LinkedIn", "ThirdParty", "Appx"),
        new("MarchofEmpires", "March of Empires", "ThirdParty", "Appx"),
        new("4DF9E0F8.Netflix", "Netflix", "ThirdParty", "Appx"),
        new("NYTCrossword", "NYT Crossword", "ThirdParty", "Appx"),
        new("OneCalendar", "One Calendar", "ThirdParty", "Appx"),
        new("PandoraMediaInc", "Pandora", "ThirdParty", "Appx"),
        new("PhototasticCollage", "Phototastic Collage", "ThirdParty", "Appx"),
        new("PicsArt-PhotoStudio", "PicsArt", "ThirdParty", "Appx"),
        new("PolarrPhotoEditorAcademicEdition", "Polarr Photo Editor", "ThirdParty", "Appx"),
        new("flaregamesGmbH.RoyalRevolt", "Royal Revolt", "ThirdParty", "Appx"),
        new("Sidia.LiveWallpaper", "Live Wallpaper", "ThirdParty", "Appx"),
        new("SlingTV", "Sling TV", "ThirdParty", "Appx"),
        new("SpotifyAB.SpotifyMusic", "Spotify", "ThirdParty", "Appx"),
        new("BytedancePte.Ltd.TikTok", "TikTok", "ThirdParty", "Appx"),
        new("TuneInRadio", "TuneIn Radio", "ThirdParty", "Appx"),
        new("WinZipUniversal", "WinZip", "ThirdParty", "Appx"),
        new("Microsoft.BingSearch", "Bing Search", "Microsoft", "Appx"),
        new("Microsoft.GamingApp", "Xbox Gaming App", "Xbox", "Appx"),
        new("Microsoft.GetHelp", "Get Help", "Microsoft", "Appx"),
        new("Microsoft.M365Companions", "Microsoft 365 Companions", "Microsoft", "Appx"),
        new("Microsoft.MSPaint", "Paint 3D", "Microsoft", "Appx"),
        new("Microsoft.OneDrive", "OneDrive", "Microsoft", "OneDrive"),
        new("Microsoft.OutlookForWindows", "Outlook for Windows", "Microsoft", "Appx"),
        new("Microsoft.Paint", "Paint", "Microsoft", "Appx"),
        new("Microsoft.People", "People", "Microsoft", "Appx"),
        new("Microsoft.RemoteDesktop", "Remote Desktop", "Microsoft", "Appx"),
        new("Microsoft.ScreenSketch", "Snipping Tool", "Microsoft", "Appx"),
        new("Microsoft.StartExperiencesApp", "Widgets Experience", "Widgets", "Appx"),
        new("Microsoft.Whiteboard", "Whiteboard", "Microsoft", "Appx"),
        new("Microsoft.Windows.Photos", "Photos", "Microsoft", "Appx"),
        new("Microsoft.WindowsCalculator", "Calculator", "Microsoft", "Appx"),
        new("Microsoft.WindowsCamera", "Camera", "Microsoft", "Appx"),
        new("Microsoft.windowscommunicationsapps", "Mail & Calendar", "Microsoft", "Appx"),
        new("Microsoft.WindowsNotepad", "Notepad", "Microsoft", "Appx"),
        new("Microsoft.Xbox.TCUI", "Xbox TCUI Framework", "Xbox", "Appx"),
        new("Microsoft.XboxGameOverlay", "Xbox Game Overlay", "Xbox", "Appx"),
        new("Microsoft.XboxGamingOverlay", "Xbox Gaming Overlay", "Xbox", "Appx"),
        new("Microsoft.XboxIdentityProvider", "Xbox Identity Provider", "Xbox", "Appx"),
        new("Microsoft.XboxSpeechToTextOverlay", "Xbox Speech To Text", "Xbox", "Appx"),
        new("Microsoft.YourPhone", "Phone Link", "Microsoft", "Appx"),
        new("Microsoft.ZuneMusic", "Media Player", "Microsoft", "Appx"),
        new("MicrosoftWindows.CrossDevice", "Cross Device Experience", "Microsoft", "Appx"),
        new("MicrosoftWindows.Client.WebExperience", "Windows Web Experience Pack", "Widgets", "Appx"),
        new("Microsoft.WidgetsPlatformRuntime", "Widgets Platform Runtime", "Widgets", "Appx"),
        new("LGElectronics.LGMonitorApp", "LG Monitor App", "OEM", "Appx"),
        new("AD2F1837.HPAIExperienceCenter", "HP AI Experience Center", "OEM", "Appx"),
        new("AD2F1837.HPConnectedMusic", "HP Connected Music", "OEM", "Appx"),
        new("AD2F1837.HPConnectedPhotopoweredbySnapfish", "HP Connected Photo", "OEM", "Appx"),
        new("AD2F1837.HPDesktopSupportUtilities", "HP Desktop Support Utilities", "OEM", "Appx"),
        new("AD2F1837.HPEasyClean", "HP Easy Clean", "OEM", "Appx"),
        new("AD2F1837.HPFileViewer", "HP File Viewer", "OEM", "Appx"),
        new("AD2F1837.HPJumpStarts", "HP JumpStarts", "OEM", "Appx"),
        new("AD2F1837.HPPCHardwareDiagnosticsWindows", "HP PC Hardware Diagnostics", "OEM", "Appx"),
        new("AD2F1837.HPPowerManager", "HP Power Manager", "OEM", "Appx"),
        new("AD2F1837.HPPrinterControl", "HP Printer Control", "OEM", "Appx"),
        new("AD2F1837.HPPrivacySettings", "HP Privacy Settings", "OEM", "Appx"),
        new("AD2F1837.HPQuickDrop", "HP QuickDrop", "OEM", "Appx"),
        new("AD2F1837.HPQuickTouch", "HP QuickTouch", "OEM", "Appx"),
        new("AD2F1837.HPRegistration", "HP Registration", "OEM", "Appx"),
        new("AD2F1837.HPSupportAssistant", "HP Support Assistant", "OEM", "Appx"),
        new("AD2F1837.HPSureShieldAI", "HP Sure Shield AI", "OEM", "Appx"),
        new("AD2F1837.HPSystemInformation", "HP System Information", "OEM", "Appx"),
        new("AD2F1837.HPWelcome", "HP Welcome", "OEM", "Appx"),
        new("AD2F1837.HPWorkWell", "HP WorkWell", "OEM", "Appx"),
        new("AD2F1837.myHP", "myHP", "OEM", "Appx"),
        new("E046963F.LenovoCompanion", "Lenovo Vantage", "OEM", "Appx"),
        new("LenovoCompanyLimited.LenovoVantageService", "Lenovo Vantage Service", "OEM", "Appx"),
        new("DellInc.DellSupportAssistforPCs", "Dell SupportAssist", "OEM", "Appx"),
        new("DellInc.DellDigitalDelivery", "Dell Digital Delivery Services", "OEM", "Appx"),
        new("DellInc.DellMobileConnect", "Dell Mobile Connect", "OEM", "Appx"),
    };
}
